- include_tasks: centos.yml
  when: (ansible_distribution == "CentOS" or ansible_distribution == "RedHat") and inventory_hostname in groups['newNode']

- include: addNode.yml
  when: inventory_hostname in groups['newNode']
