- name: 安装haproxy
  include_tasks: haproxy.yml

- name: 安装keepalived
  include_tasks: keepalived.yml

- name: 启动haproxy keepalived
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - keepalived
    - haproxy

- wait_for: 
    host: "{{ VIP }}"
    delay: 10
    port: 22
  connection: local

#- name: ping测试VIP
#  net_ping:
#    dest: "{{ VIP }}"
#  connection: local
